var situacion='"<p>Los lineamientos editoriales de cada revista acad&eacute;mica dirigen la redacci&oacute;n del art&iacute;culo en cuanto a estructura y elementos formales; por lo tanto, es recomendable que los autores tengan seleccionada la revista en la que quieren colaborar para atender a los criterios editoriales de la misma.</p><p>&iquest;C&oacute;mo organizar esta b&uacute;squeda para hacer una selecci&oacute;n adecuada a tus intereses acad&eacute;micos?</p><p>Este curso presenta algunas herramientas virtuales para la búsqueda de revistas académicas y la valoración de estándares de calidad, de manera que el participante defina su criterio de selección para elegir en dónde desea publicar su artículo, considerando su propuesta temática, el área de conocimiento y la línea de investigación.</p>"';
const contenidoEE = '{"tituloPresentacion":"Producción de artículos académicos con fines de publicación",'+
                    '"textoProposito":"<p>El participante identifica los lineamientos editoriales en tres revistas académicas especializadas de su elección, para redactar el artículo académico a publicar.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Selección de revista académica especializada",'+
                    '"tituloModulo2":"Módulo 2: Planteamiento del problema y estado del arte",'+
                    '"tituloModulo3":"Módulo 3: Materiales y métodos, presentación de resultados y discusión.",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
