var situacion='"<p>La salud es un derecho humano, no obstante la marcada desigualdad ha generado que no todas las personas puedan acceder a ella. Por ello, diversos organismos a nivel internacional han intentado cerrar estas brechas. As&iacute;, en esta Experiencia Educativa&nbsp; (EE) revisaremos:</p><ol><li>&iquest;De qu&eacute; manera se relacionan la equidad y la salud?</li><li>&iquest;C&oacute;mo est&aacute; vinculada la salud y los derechos humanos?</li><li>&iquest;Qu&eacute; factores influyen para que en una comunidad la equidad en salud se d&eacute; de manera positiva?</li><li>&iquest;Qu&eacute; se ha hecho a nivel nacional e internacional para lograr la equidad en salud?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Equidad en salud",'+
                    '"textoProposito":"<p>El alumno analiza los conceptos equidad y salud, contextualizándolos en los acuerdos globales nacionales e internacionales, así como los derechos humanos, destacando su importancia dentro del campo laboral y en su vida cotidiana.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Antecedentes a la equidad y salud.",'+
                    '"tituloModulo2":"Módulo 2: Aportes universitarios a la equidad en salud y los derechos humanos.",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
