var situacion='"<p>La equidad en salud implica que, idealmente, todos deben tener una oportunidad justa para lograr plenamente su potencial en salud y, de modo más pragmático, que nadie debe estar desfavorecido para lograrlo en la medida en que ello pueda evitarse. Con base en esta definición, el objetivo de la política para equidad y salud no consiste en eliminar todas las diferencias en este sector para que así todos posean el mismo nivel y calidad de bienestar, sino que pretende reducir o eliminar aquéllas que resultan de los factores que se consideran tanto evitables como injustos.</p><p>En este sentido, una v&iacute;a para promover la salud y la equidad es generar consciencia sobre todos los factores y modelos de bienestar que tienen repercusiones en &eacute;sta, lo que vuelve fundamental su difusi&oacute;n y el fomento de la autogesti&oacute;n a trav&eacute;s de planes que la fortalezcan.</p>"';
const contenidoEE = '{"tituloPresentacion":"Equidad en salud",'+
                    '"textoProposito":"<p>El alumno se hace consciente de todos los factores que afectan su salud integral a partir de los modelos de bienestar propuestos, mediante la generación de un plan de salud individual y un proyecto comunitario, para apoyar al bienestar humano y planetario y la equidad en salud.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Antecedentes a la equidad y salud.",'+
                    '"tituloModulo2":"Módulo 2: Aportes universitarios a la equidad en salud y los derechos humanos.",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
