var situacion='"<p><strong>Inclusi&oacute;n en nuestra </strong><strong>u</strong><strong>niv</strong><strong>ersidad</strong></p><p>Observe el video <em>Inclusi&oacute;n en la universidad </em>(Tomadin, 2015):</p><p>Despu&eacute;s de ver el video reflexione los siguientes cuestionamientos:</p><div class=\'centrado\'><iframe width=\'560\' height=\'315\' src=\'https://www.youtube.com/embed/uPZpAJ9IKTo\' title=\'YouTube video player\' frameborder=\'0\' allow=\'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\' allowfullscreen></iframe></div><ol><li style= \'text-align: left;\'>La entidad acad&eacute;mico donde laboro, &iquest;es un espacio de inclusi&oacute;n que favorece el aprendizaje para todos?</li><li style= \'text-align: left;\'>&iquest;Qu&eacute; acciones se realizan en la entidad acad&eacute;mica para construir una cultura de inclusi&oacute;n?</li><li style= \'text-align: left;\'>&iquest;C&oacute;mo percibo el discurso y la pr&aacute;ctica institucional de la Universidad Veracruzana respecto de la inclusi&oacute;n educativa de personas con discapacidad?</li><li style= \'text-align: left;\'>&iquest;Cu&aacute;l es el alcance de mi participaci&oacute;n para consolidar una cultura de inclusi&oacute;n en la Universidad Veracruzana?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Educación Superior Inclusiva",'+
                    '"textoProposito":"<p>Los participantes obtienen herramientas teórico-prácticas para transversalizar las dimensiones de la inclusión en el quehacer de todas las actividades educativas y elaborar estrategias que permitan potenciar el aprendizaje y la participación de todos,  avanzando hacia una universidad más incluyente y respetuosa de la diversidad. </p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Fase 1. Inclusión y diversidad en la política educativa",'+
                    '"tituloModulo2":"Fase 2. Las IES y la atención a la discapacidad",'+
                    '"tituloModulo3":"Fase 3. Dimensiones para establecer sistemas educativos inclusivos",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
