const contenidoEE = '{"tituloPresentacion":"Educación inclusiva",'+
                    '"textoPresentacion":"<img src= \'imagenes/presentacion.png\' align=\'left\' hspace=\'50\' vpsace=\'50\' style=\'width: 30%\'><p>La presente Experiencia Educativa est&aacute; dise&ntilde;ada para impartirse a toda la comunidad acad&eacute;mica de la Universidad Veracruzana que desea contar con una formaci&oacute;n b&aacute;sica sobre Educaci&oacute;n inclusiva, a trav&eacute;s del programa de Formaci&oacute;n de Acad&eacute;micos (ProFA) de la Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa, bajo una modalidad virtual, manteniendo una comunicaci&oacute;n sincr&oacute;nica mediante la herramienta <em>Zoom</em> con una duraci&oacute;n de 20 horas.</p><p>Dicha EE tiene como finalidad:</p><ol><li>Formar al personal acad&eacute;mico en materia de inclusi&oacute;n, &ldquo;principio transversal en la educaci&oacute;n y en los sistemas educativos, con el fin de trabajar juntos en beneficio de toda la poblaci&oacute;n universitaria y garantizar la igualdad de acceso, participaci&oacute;n y resultados de aprendizaje, haciendo frente a todas las formas de discriminaci&oacute;n, exclusi&oacute;n y marginaci&oacute;n entre los integrantes de la comunidad universitaria, particularmente entre aquellos que viven con discapacidad&rdquo; (Declaraci&oacute;n de Incheon, 2015).</li><li>Fortalecer el desarrollo de competencias &eacute;ticas necesarias y a trav&eacute;s de saberes te&oacute;ricos, axiol&oacute;gicos y heur&iacute;sticos, para contribuir con la formaci&oacute;n a la construcci&oacute;n de una sociedad diversa y democr&aacute;tica, favoreciendo climas escolares y laborales de respeto y confianza, aprendizaje mutuo, actitudes y valores inclusivos como la igualdad, equidad, colaboraci&oacute;n, no discriminaci&oacute;n y el respeto a los derechos humanos y a la diversidad.</li></ol>",'+
                    '"textoUnidad":"<img src= \'imagenes/unidad.png\' align=\'left\' hspace=\'50\' vpsace=\'50\' style=\'width: 30%\'><p>El personal acad&eacute;mico desarrollar&aacute; herramientas te&oacute;ricas y metodol&oacute;gicas necesarias para identificar retos y oportunidades con el fin de elaborar propuestas para favorecer el proceso de inclusi&oacute;n de estudiantes con discapacidad en la Universidad Veracruzana, demostrando sensibilidad en la construcci&oacute;n de una comunidad educativa amigable y accesible para las personas con discapacidad, mediante planificaci&oacute;n, organizaci&oacute;n y trabajo en equipo.</p><p>(PTE 2017-2021, Eje estrat&eacute;gico II, programa 7, l&iacute;nea de acci&oacute;n 18).</p>",'+
                    '"tituloModulo1":"Fase 1: Inclusión y diversidad en la política educativa",'+
                    '"tituloModulo2":"Fase 2: Las IES y la atención a la discapacidad",'+
                    '"tituloModulo3":"Fase 3. Dimensiones para establecer sistemas educativos inclusivos",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra</strong><strong>. Elena </strong><strong>Rustri&aacute;n</strong><strong> Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez </strong><strong>Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><strong>Dra</strong><strong>. Elizabeth </strong><strong>Ocampo G&oacute;mez</strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas </strong><strong>Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli </strong><strong>Arg&uuml;ello </strong><strong>Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Dra</strong><strong>. Mar&iacute;a Jos&eacute; Garc&iacute;a Oramas</strong><br><strong>Mtra. Gloria P&eacute;rez Olivares</strong><br><strong>Mtra. Vianey Illescas De Felipe</strong><br><strong>Dr. Amador Jes&uacute;s Gonz&aacute;lez Hern&aacute;ndez Gonz&aacute;lez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo </strong><strong>Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo </strong><strong>Hern&aacute;ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora </strong><strong>Rodr&iacute;guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. </strong><strong>J&oacute;nathan </strong><strong>Iv&aacute;n </strong><strong>Guti&eacute;rrez </strong><strong>Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas </strong><strong>G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n"'+
                '}';


                