var situacion='"<p>Comencemos por reconocer la situaci&oacute;n objetiva que abordaremos en este curso e identificar los motivos personales y profesionales implicados en esta experiencia de aprendizaje.</p><p>Observe el video <em>Makes the World more vibrant</em>.</p><div class=\'centrado\'><iframe width=\'560\' height=\'315\' src=\'https://www.youtube.com/embed/QXY5TyCUTlo\' title=\'YouTube video player\' frameborder=\'0\' allow=\'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\' allowfullscreen></iframe></div><p>Despu&eacute;s, t&oacute;mese unos minutos para reflexionar acerca de la situaci&oacute;n presentada en dicho video y reconocer c&oacute;mo se manifiesta el hecho en su contexto: familiar, personal, escolar y laboral.</p><p><strong>Reflexione los siguientes cuestionamientos:</strong></p><ol><li style= \'text-align: left;\'>De lo descrito en el video, &iquest;qu&eacute; es significativo para m&iacute;?</li><li style= \'text-align: left;\'>&iquest;C&oacute;mo se relaciona la situaci&oacute;n presentada en el video con mi vida cotidiana?</li><li style= \'text-align: left;\'>&iquest;Qu&eacute; motivos personales&nbsp; sobre el tema animan mi participaci&oacute;n en este curso?</li><li style= \'text-align: left;\'>&iquest;Qu&eacute; motivos profesionales sobre el tema animan mi participaci&oacute;n en este curso?</li></ol><p>Comparta sus respuestas en el Foro de presentaci&oacute;n: Discapacidad, una emergencia que nos involucra.</p>"';
const contenidoEE = '{"tituloPresentacion":"Educación Superior Inclusiva",'+
                    '"textoProposito":"<p>El participante aborda los elementos teóricos, prácticos y normativos acerca del proceso de la educación inclusiva a nivel superior con la finalidad de favorecer ambientes escolares y laborales en compromiso con la igualdad y la no discriminación, disminuyendo barreras personales, académicas, sociales y profesionales.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Fase 1. Inclusión y diversidad en la política educativa",'+
                    '"tituloModulo2":"Fase 2. Las IES y la atención a la discapacidad",'+
                    '"tituloModulo3":"Fase 3. Dimensiones para establecer sistemas educativos inclusivos",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
