var situacion='"<p><strong>Dificultades de las </strong><strong>personas </strong><strong>con </strong><strong>discapacidad </strong><strong>en las IES</strong></p><p>Observe el siguiente video en el que un estudiante con discapacidad, de la Universidad de Guadalajara, expone algunas de las dificultades que enfrenta para desarrollar sus actividades escolares.</p><div class=\'centrado\'><iframe width=\'560\' height=\'315\' src=\'https://www.youtube.com/embed/HnQO5LfkWa0\' title=\'YouTube video player\' frameborder=\'0\' allow=\'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\' allowfullscreen></iframe></div><ol><li>&iquest;Conoce alguna situaci&oacute;n similar en la Universidad Veracruzana? &iquest;Qu&eacute; se ha hecho al respecto?</li><li>&iquest;Sabe cu&aacute;les son las estrategias que impulsa la Universidad Veracruzana para garantizar el derecho a la educaci&oacute;n superior de las personas con discapacidad?</li></ol><p><strong>Inclusi&oacute;n, el compromiso de las IES</strong></p><p>En 2008, representantes de Instituciones de Educaci&oacute;n Superior (IES) de M&eacute;xico firmaron la <em>Declaraci&oacute;n de Yucat&aacute;n</em>, comprometi&eacute;ndose a garantizar el acceso en igualdad de oportunidades de estudiantes con discapacidad.</p><p>La Universidad Veracruzana ha asumido ese compromiso a trav&eacute;s del <em>Programa Universitario para la Inclusi&oacute;n de Personas con Discapacidad </em>(PUEI), actualmente a cargo del Centro para el Desarrollo Humano e Integral de los Universitarios (CENDHIU).</p><ol><li>&iquest;Conoce el contenido de la <em>Declaraci&oacute;n de Yucat&aacute;n</em>?</li><li>&iquest;Sabe en qu&eacute; consiste el <em>Programa Universitario para la Inclusi&oacute;n de Personas con Discapacidad</em> de la UV?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Educación inclusiva",'+
                    '"textoProposito":"<p>Los participantes adquieren conocimientos teóricos sobre los lineamientos que poseen las Instituciones de Educación Superior (IES) en materia de discapacidad, así como las habilidades psicopedagógicas para detectar y atender las barreras de aprendizaje y participación desde sus ámbitos universitarios.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Fase 1. Inclusión y diversidad en la política educativa",'+
                    '"tituloModulo2":"Fase 2. Las IES y la atención a la discapacidad",'+
                    '"tituloModulo3":"Fase 3. Dimensiones para establecer sistemas educativos inclusivos",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
