const contenidoEE = '{"tituloPresentacion":"Educación Superior Inclusiva",'+
                    '"textoPresentacion":"<img src= \'imagenes/presentacion.png\' align=\'left\' hspace=\'50\' vpsace=\'50\' style=\'width: 30%\'><p>La presente Experiencia Educativa est&aacute; dise&ntilde;ada para impartirse a toda la comunidad acad&eacute;mica de la Universidad Veracruzana que desea contar con una formaci&oacute;n b&aacute;sica sobre Educaci&oacute;n inclusiva, a trav&eacute;s del Programa de Formaci&oacute;n de Acad&eacute;micos (ProFA) de la Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa, bajo la modalidad virtual, manteniendo una comunicaci&oacute;n sincr&oacute;nica mediante la herramienta <em>Zoom</em> y con una duraci&oacute;n de 30 horas.</p><p>Dicha EE tiene como finalidad:</p><ol><li>Formar al personal acad&eacute;mico en materia de inclusi&oacute;n, &ldquo;principio transversal en la educaci&oacute;n y en los sistemas educativos, con el fin de trabajar juntos en beneficio de toda la poblaci&oacute;n universitaria y garantizar la igualdad de acceso, participaci&oacute;n y resultados de aprendizaje, haciendo frente a todas las formas de discriminaci&oacute;n, exclusi&oacute;n y marginaci&oacute;n entre los integrantes de la comunidad universitaria, particularmente entre aquellos que viven con discapacidad&rdquo; (Declaraci&oacute;n de Incheon, 2015).</li><li>Fortalecer el desarrollo de competencias &eacute;ticas necesarias y a trav&eacute;s de saberes te&oacute;ricos, axiol&oacute;gicos y heur&iacute;sticos, para contribuir en la construcci&oacute;n de una sociedad diversa y democr&aacute;tica, favoreciendo climas escolares y laborales de respeto y confianza, aprendizaje mutuo, actitudes y valores inclusivos como la igualdad, equidad, colaboraci&oacute;n, no discriminaci&oacute;n y el respeto a los derechos humanos y a la diversidad.</li></ol>",'+
                    '"textoUnidad":"<img src= \'imagenes/unidad.png\' align=\'left\' hspace=\'50\' vpsace=\'50\' style=\'width: 30%\'><br><br><br><br><br><p>El personal acad&eacute;mico desarrollar&aacute; herramientas te&oacute;ricas y metodol&oacute;gicas necesarias para identificar retos y oportunidades con el fin de elaborar propuestas para favorecer el proceso de inclusi&oacute;n de estudiantes con discapacidad en la Universidad Veracruzana, demostrando sensibilidad en la construcci&oacute;n de una comunidad educativa amigable y accesible, mediante planificaci&oacute;n, organizaci&oacute;n y trabajo en equipo.</p><p>(PTE 2017-2021, Eje estrat&eacute;gico II, programa 7, l&iacute;nea de acci&oacute;n 18).</p>",'+
                    '"tituloModulo1":"Fase 1: Inclusión y diversidad en la política educativa",'+
                    '"tituloModulo2":"Fase 2: Las IES y la atención a la discapacidad",'+
                    '"tituloModulo3":"Fase 3. Dimensiones para establecer sistemas educativos inclusivos",'+
                    '"textoCreditos":"<p><strong>Universidad Veracruzana</strong></p><p>&nbsp;</p><p><strong>Dra. Elena Rustri&aacute;n Portilla</strong></p><p>Secretar&iacute;a Acad&eacute;mica</p><p><strong>Mtra. Carla M&oacute;nica G&oacute;mez Salgado</strong></p><p>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea</p><p>&nbsp;</p><p><strong>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)</strong></p><p>&nbsp;</p><p><strong>Dra. Elizabeth Ocampo G&oacute;mez </strong><br /> Direcci&oacute;n General</p><p><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong></p><p>Direcci&oacute;n de Innovaci&oacute;n Educativa</p><p><strong>Mtra. Araceli Arg</strong><strong>&uuml;ello Aguilar</strong></p><p>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico</p><p><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong></p><p>Departamento de Formaci&oacute;n Acad&eacute;mica</p><p>&nbsp;</p><p><strong>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos</strong></p><p>&nbsp;</p><p><strong>Dr. Amador Jes&uacute;s Gonz&aacute;lez Hern&aacute;ndez</strong></p><p><strong>Dra. Mar&iacute;a Jos&eacute; Garc&iacute;a Oramas</strong></p><p><strong>Mtra. Gloria P&eacute;rez Olivares</strong></p><p><strong>Mtra. Vianey Illescas De Felipe</strong></p><p>Expertos en contenido</p><p>&nbsp;</p><p><strong>C&eacute;lula de desarrollo de Experiencias Educativas virtuales de la DGDAIE</strong></p><p><strong>&nbsp;</strong></p><p><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong></p><p>Coordinaci&oacute;n de C&eacute;lula de desarrollo</p><p><strong>Mtro. Mario Evaristo Gonz</strong><strong>&aacute;lez M</strong><strong>&eacute;ndez </strong></p><p>Dise&ntilde;o instruccional</p><p><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;ndez</strong></p><p>Gesti&oacute;n de contenido</p><p><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;guez</strong></p><p>Correcci&oacute;n de estilo</p><p><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong></p><p>Dise&ntilde;o gr&aacute;fico</p><p><strong>Mtro. J</strong><strong>onathan Iv&aacute;n Guti</strong><strong>&eacute;rrez Palma</strong></p><p>Experto en medios</p><p><strong>Mtro. Renato Vargas G</strong><strong>&oacute;mez</strong></p><p>Programaci&oacute;n</p>"'+
                '}';


                