var situacion='"<p>La educaci&oacute;n universitaria busca especializar al estudiante y prepararlo para la vida profesional. Sin embargo, es de vital importancia se&ntilde;alar&nbsp; que la universidad tambi&eacute;n debe promover el pensamiento cr&iacute;tico del estudiante y ayudarle a conocer y reflexionar acerca de temas generales de inter&eacute;s com&uacute;n.</p><p>Acerca de lo menciona, reflexiona sobre las siguientes preguntas:</p><ol><li>&iquest;Qu&eacute; es la bilog&iacute;a?</li><li>&iquest;Entiendes el concepto de Neurociencias?</li><li>&iquest;Conoces ampliamente el tema de la sexualidad?</li><li>&iquest;Cu&aacute;l es la utilidad del idioma ingl&eacute;s en tu vida?</li><li>&iquest;Tienes claridad acerca del cuidado del medio ambiente?</li><li>&iquest;Qu&eacute; son y c&oacute;mo influyen en tu vida los h&aacute;bitos de consumo?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Cómo ser responsable y disfrutar la vida",'+
                    '"textoProposito":"<p>El estudiante practica el pensamiento crítico, a través de la reflexión derivada del abordaje de temas relaciona con la Biología, Neurociencias, Sexualidad, Idioma inglés y Medio ambiente y hábitos de consumo.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Desarrollo personal",'+
                    '"tituloModulo2":"Módulo 2: Conocimiento general",'+
                    '"tituloModulo3":"Módulo 3: Responsabilidades de adulto",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
