var situacion='"<p>Todo conflicto, tanto externo como interno, se origina en la relación con otro individuo, con el medio ambiente y hasta con uno mismo. Uno de los principales objetivos de este módulo es que como estudiante identifiques tus conflictos y desarrolles las habilidades de contacto, tales como: darse cuenta, separar pensamientos de emociones, comunicarse de forma clara y directa, responder, escuchar, pedir, recibir, dar, manejar el conflicto, ser asertivo y dar apoyo. En consecuencia, es importante que explores tus emociones, que seas capaz de vivenciarlas y separarlas de tus pensamientos, que conozcas y ejercites conductas y comunicación asertiva y que ejerzas tus derechos personales.</p><p>Para ello, inicia pregunt&aacute;ndote:</p><ol style=\'text-align: left;\'><li>&iquest;Qu&eacute; tan flexible es mi pensamiento?</li><li>&iquest;Cu&aacute;les son las emociones b&aacute;sicas?</li><li>&iquest;En qu&eacute; parte de mi cuerpo siento cada emoci&oacute;n?</li><li>&iquest;Distingo lo que pienso de lo que siento?</li><li>&iquest;C&oacute;mo escucho al otro?</li><li>&iquest;C&oacute;mo me escucho a m&iacute; mismo?</li><li>&iquest;C&oacute;mo pido? &iquest;C&oacute;mo recibo? &iquest;C&oacute;mo doy?</li><li>&iquest;S&eacute; manejar el conflicto?</li><li>&iquest;Qu&eacute; es para m&iacute; la asertividad?</li><li>&iquest;C&oacute;mo doy apoyo?</li><li>&iquest;S&eacute; cu&aacute;les son mis derechos personales?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Cómo ser responsable y disfrutar la vida",'+
                    '"textoProposito":"<p>El estudiante identifica habilidades de contacto, estrategias de comunicación, emociones y derechos personales, mediante el análisis, reflexión y autoevaluación para contribuir a su desarrollo personal. </p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Desarrollo personal",'+
                    '"tituloModulo2":"Módulo 2: Conocimiento general",'+
                    '"tituloModulo3":"Módulo 3: Responsabilidades de adulto",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
