var situacion='"<p>Convertirse en un adulto responsable significa que, adem&aacute;s de desarrollarnos profesional y personalmente, nos volvemos conscientes del entorno que nos rodea y de nuestro papel dentro de &eacute;l. Una de las responsabilidades que se contraen en la vida adulta consiste en cuidar el dinero, planear nuestro futuro, ser ciudadanos responsables y seres humanos emp&aacute;ticos. Sin embargo, &iquest;en d&oacute;nde nos ense&ntilde;an a reflexionar sobre nuestras obligaciones? &iquest;En d&oacute;nde nos ense&ntilde;an a planear nuestro futuro?</p><p>Para ayudar a que podamos responder lo anterior, en este m&oacute;dulo integraremos los siguientes saberes:</p><ol style=\'text-align: left;\'><li>&iquest;C&oacute;mo distribuir el ingreso? &iquest;Qu&eacute; es y c&oacute;mo usar el cr&eacute;dito?</li><li>Responsabilidades de adulto: predial, impuestos, tenencia.</li><li>Tus derechos y obligaciones en la Constituci&oacute;n. Reglamento de tr&aacute;nsito: peat&oacute;n y conductor y, finalmente.</li><li>&iquest;C&oacute;mo elegir pareja?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Cómo ser responsable y disfrutar la vida",'+
                    '"textoProposito":"<p>El estudiante reflexiona acerca de las responsabilidades de la vida adulta, conociendo y analizando  información concerniente a cómo distribuir su ingreso, cómo usar el crédito, el concepto de individuo y de sociedad, obligaciones y derechos ciudadanos, del peatón, del conductor y cómo elegir pareja. </p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Desarrollo personal",'+
                    '"tituloModulo2":"Módulo 2: Conocimiento general",'+
                    '"tituloModulo3":"Módulo 3: Responsabilidades de adulto",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
