var situacion='"<p>&iquest;Ha escrito o intentado escribir un texto acad&eacute;mico para publicar los resultados de su investigaci&oacute;n?, &iquest;qu&eacute; dificultades ha encontrado en el proceso de escritura acad&eacute;mica?, &iquest;ha tenido formaci&oacute;n espec&iacute;fica para la redacci&oacute;n de textos acad&eacute;micos?</p><p>Observe el video <em>Investigar para escribir </em>(Did&aacute;ctica y nuevas tecnolog&iacute;a, 2014):</p><div style=\'text-align: center;\'><iframe width=\'560\' height=\'315\' src=\'https://www.youtube.com/embed/iQ1DH1cZtlc\' title=\'YouTube video player\' frameborder=\'0\' allow=\'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\' allowfullscreen></iframe></div><p>Investigar y escribir son competencias fundamentales para incursionar profesionalmente como investigador en cualquier &aacute;rea de conocimiento. Por eso, adem&aacute;s del saber disciplinario, es necesario desarrollar habilidades espec&iacute;ficas para obtener, organizar y presentar informaci&oacute;n; adem&aacute;s de saber comunicar el proceso y los hallazgos del trabajo de investigaci&oacute;n.</p><p>En este m&oacute;dulo abordaremos aspectos formales de la fase documental de la escritura acad&eacute;mica: planteamiento del problema y estado del arte.</p><p>&iquest;Qu&eacute; sabe sobre el tema?, &iquest;qu&eacute; dificultades ha enfrentado en la construcci&oacute;n y redacci&oacute;n de estos dos elementos del texto acad&eacute;mico?</p>"';
const contenidoEE = '{"tituloPresentacion":"Written and oral expression in english in the working context",'+
                    '"textoProposito":"<p>Students will develop theoretical and practical knowledge to write documents at work:  Memorandum, formal letter, circular, minute, notice, reports and e-mails.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Module 1: Personal documents used at work.",'+
                    '"tituloModulo2":"Module 2: Workplace documents.",'+
                    '"tituloModulo3":"Module 3: Workplace communication.",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
