var situacion='"<p>We all know&nbsp;how to write&nbsp;documents&nbsp;in our native language and we also know&nbsp;what expressions&nbsp;or vocabulary to use when we write. We&nbsp;can write&nbsp;reference letters, curriculum vitae, request land complain letters, however, do we know how to write them in English? It is very important to know what expressions, vocabulary and what format&nbsp;can be used in each&nbsp;case. The reason? In English&nbsp; these documents /papers have to be written in a different way.&nbsp;&nbsp;Let\'s see&nbsp;an example:&nbsp;</p><p>Watch the attached video and answer these questions:</p><div style=\'text-align: center;\'><iframe title=\'YouTube video player\' src=\'https://www.youtube.com/embed/1a9vZG8iPN8\' width=\'560\' height=\'315\' frameborder=\'0\' allowfullscreen=\'allowfullscreen\'></iframe></div><ol><li>According to the video what is a curriculum vitae (CV)?</li><li>How long is a CV&nbsp; in the United Kingdom?</li><li>What does the CV contain?</li><li>When is the CV generally used?</li><li>When is the resume generally used?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Expresión escrita y oral en inglés en el ámbito laboral",'+
                    '"textoProposito":"<p>Students will  develop theoretical and practical knowledge to write  documents used in the working context: Reference letters, application letter,  curriculum vitae, resume, request letter and complain letter.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Module 1: Personal documents used at work.",'+
                    '"tituloModulo2":"Module 2: Workplace documents.",'+
                    '"tituloModulo3":"Module 3: Workplace communication.",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
