var situacion='"<p><strong>Reflect on the following questions:</strong></p><ol><li>Have you ever asked yourself the following questions?</li><li>What should you do when having oral presentations?</li><li>What are some basic skills for effective oral presentations?</li><li>What skills must you develop in order to conduct effective meetings?</li><li>What do you need to know for holding a successful interview?&nbsp;</li></ol><p>Nowadays getting a high-flying job is becoming one of the most essential objectives for everybody and specially for people who have recently finished their studies, however how can they make a skilled impression at an interview? And once they get the job what do they&nbsp; need to consider to present their results or conduct meetings at work? In this module, you can study and learn some significant facts to consider for those situations in the work context.</p>"';
const contenidoEE = '{"tituloPresentacion":"Written and oral expression in english in the working context",'+
                    '"textoProposito":"<p>Students will develop theoretical and practical knowledge to communicate effectively and efficiently in job interviews, meetings and oral presentations at work.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Module 1: Personal documents used at work.",'+
                    '"tituloModulo2":"Module 2: Workplace documents.",'+
                    '"tituloModulo3":"Module 3: Workplace communication.",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
