var situacion='"<p><strong>Observe el siguiente video en el que se explica la importancia del an&aacute;lisis financiero y algunas de sus caracter&iacute;sticas. Luego reflexione:</strong></p><ul><li>&iquest;Cu&aacute;l es la importancia de realizar un an&aacute;lisis financiero dentro de una empresa?</li><li>&iquest;De qu&eacute; manera influye la informaci&oacute;n que nos proporcionan los estado financieros para la toma de decisiones dentro de una empresa?</li><li>&iquest;C&oacute;mo espera que este curso le ayude a superar los nuevos retos de sostenibilidad financiera a los que se enfrentan las empresas?</li></ul><p>&nbsp;</p><div style=\'text-align: center;\'><iframe title=\'YouTube video player\' src=\'https://www.youtube.com/embed/vxp6jeVAEQE\' width=\'560\' height=\'315\' frameborder=\'0\' allowfullscreen=\'allowfullscreen\'></iframe></div>"';
const contenidoEE = '{"tituloPresentacion":"Análisis financiero para la toma de decisiones",'+
                    '"textoProposito":"<p>El participante conoce las nociones generales de los estados financieros, tales como: sus características, estructura, formas de presentación y quiénes son los usuarios de la información financiera, para identificar los elementos e indicadores útiles en el proceso de toma de decisiones en la empresa.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Estructura de los estados financieros",'+
                    '"tituloModulo2":"Módulo 2: Análisis financiero",'+
                    '"tituloModulo3":"Módulo 3: Herramientas adicionales",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
