var situacion='"<p>El siguiente video expone la importancia de calcular el <strong>punto de equilibrio </strong>financiero en cualquier emprendimiento, rev&iacute;selo atentamente.</p><div style=\'text-align: center;\'><iframe title=\'YouTube video player\' src=\'https://www.youtube.com/embed/R1fudBO1Fpk\' width=\'560\' height=\'315\' frameborder=\'0\' allowfullscreen=\'allowfullscreen\'></iframe></div><p><strong>Reflexiona:</strong></p><ol><li>&iquest;Ha emprendido alg&uacute;n negocio?, &iquest;en qu&eacute; informaci&oacute;n se ha basado para la toma de decisiones financieras respecto de su negocio?</li><li>&iquest;Ha calculado el punto de equilibrio de su emprendimiento?</li><li>&iquest;Considera que esta informaci&oacute;n financiera ser&iacute;a &uacute;til para los emprendedores en las PyMEs?, &iquest;por qu&eacute;?</li></ol>"';
const contenidoEE = '{"tituloPresentacion":"Análisis financiero para la toma de decisiones",'+
                    '"textoProposito":"<p>El participante conoce algunas herramientas alternativas de gran utilidad para el an&aacute;lisis financiero: el <strong>punto de equilibrio </strong>y el <strong>M&eacute;todo Z2 Altman</strong>, que aportan informaci&oacute;n relevante para la toma de decisiones financieras.</p>",'+
                    '"textoSituacion":'+ situacion + ','+
                    '"tituloModulo1":"Módulo 1: Estructura de los estados financieros",'+
                    '"tituloModulo2":"Módulo 2: Análisis financiero",'+
                    '"tituloModulo3":"Módulo 3: Herramientas adicionales",'+
                    '"textoCreditos":"<strong>Cr&eacute;ditos</strong><br><strong>Universidad Veracruzana</strong><br><br /> <strong>Dra. Elena Rustri&aacute;n Portilla</strong><br>Secretar&iacute;a Acad&eacute;mica<br><strong>Mtra. </strong><strong>Carla M&oacute;nica G&oacute;mez Salgado</strong><br>Coordinaci&oacute;n General de Educaci&oacute;n en L&iacute;nea<br><br /> <strong>Dra. Elizabeth Ocampo&nbsp; </strong><br>Direcci&oacute;n General de Desarrollo Acad&eacute;mico e Innovaci&oacute;n Educativa (DGDAIE)<br><strong>Mtro. Miguel &Aacute;ngel Barradas Ger&oacute;n</strong><br>Direcci&oacute;n de Innovaci&oacute;n Educativa<br><strong>Mtra. Araceli Arg&uuml;ello Aguilar</strong><br>Direcci&oacute;n de Fortalecimiento Acad&eacute;mico<br><strong>Mtro. Rafael Lucio P&eacute;rez Rojas</strong><br>Departamento de Formaci&oacute;n Acad&eacute;mica<br><strong>C&eacute;lula de Desarrollo de Experiencias Educativas Virtuales de la DGDAIE</strong><br><strong>Mtra. Yahel Teresa Vichi Mart&iacute;nez</strong><br>Autor&iacute;a de la Experiencia Educativa del Programa de Formaci&oacute;n de Acad&eacute;micos<br><strong>Mtro. Mario Evaristo Gonz&aacute;lez M&eacute;ndez </strong><br>Dise&ntilde;o instruccional<br><strong>Mtro. Josafat Murillo Hern</strong><strong>&aacute;</strong><strong>ndez</strong><br>Gesti&oacute;n de contenido<br><strong>Mtra. Alicia Mora Rodr</strong><strong>&iacute;</strong><strong>guez</strong><br>Correcci&oacute;n de estilo<br><strong>Mtro. Aurelio Hern&aacute;ndez Guerrero</strong><br>Dise&ntilde;o gr&aacute;fico<br><strong>Mtro. J&oacute;nathan Iv&aacute;n Guti&eacute;rrez Palma</strong><br>Experto en medios<br><strong>Mtro. Renato Vargas G&oacute;mez</strong><br>Programaci&oacute;n<br><strong>Mtra. Luz Mariela Cabrera Hern&aacute;ndez</strong><br>Coordinaci&oacute;n<br>"'+
                '}';






                
